spring.datasource.url: jdbc:${DATABASE_URL}
spring.datasource.username: root
spring.datasource.password: qwerty
spring.datasource.driver-class-name: org.postgresql.Driver
server.port: ${PORT:8080}

spring.jpa.database: postgresql
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.hibernate.ddl-auto: validate

spring.servlet.multipart.max-file-size: 128MB
spring.servlet.multipart.max-request-size: 128MB
spring.servlet.multipart.enabled: true

spring.liquibase.change-log: "classpath:db/changelog/db.changelog-master.xml"

blog.mail.password: ${MAIL_PASSWORD}
blog.mail.restoreUrl: ${RESTORE_URL}

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005

captcha.lifetimeBySec: 3600